//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMCore.Server.ResX.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResX_Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResX_Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JMCore.Server.ResX.Resources.ResX_Errors", typeof(ResX_Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server side error..
        /// </summary>
        public static string ApiResponseBaseStatusCode_ERROR_BADREQUEST_RESPONSE {
            get {
                return ResourceManager.GetString("ApiResponseBaseStatusCode_ERROR_BADREQUEST_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string ApiResponseBaseStatusCode_ERROR_INTERNALSERVERERROR_RESPONSE {
            get {
                return ResourceManager.GetString("ApiResponseBaseStatusCode_ERROR_INTERNALSERVERERROR_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error..
        /// </summary>
        public static string ApiResponseBaseStatusCode_ERROR_OTHER_RESPONSE {
            get {
                return ResourceManager.GetString("ApiResponseBaseStatusCode_ERROR_OTHER_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse JSON fail..
        /// </summary>
        public static string ApiResponseBaseStatusCode_ERROR_PARSEJSON {
            get {
                return ResourceManager.GetString("ApiResponseBaseStatusCode_ERROR_PARSEJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not authorized..
        /// </summary>
        public static string ApiResponseBaseStatusCode_ERROR_UNAUTHORIZED_RESPONSE {
            get {
                return ResourceManager.GetString("ApiResponseBaseStatusCode_ERROR_UNAUTHORIZED_RESPONSE", resourceCulture);
            }
        }
    }
}
