version: "3.8"
name: jmcoretest
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - jmcore_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: no
    ports:
      - "5434:5433"
    environment:
      PGADMIN_DEFAULT_EMAIL: jiri.machacek@machysoft.cz
      PGADMIN_DEFAULT_PASSWORD: Heslo1234.
      PGADMIN_LISTEN_PORT: 5434
    volumes:
      - jmcore_pgadmin:/var/lib/pgadmin
  mongo:
    image: mongo:latest
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - jmcore-mongodata:/data/db
   
volumes:
  jmcore_pgdata:
  jmcore_pgadmin:
  jmcore-mongodata:  