version: "3.8"
name: postgres2
services:
  db:
    image: postgres
    container_name: postgres2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - local_pgdata2:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container2
    restart: always
    ports:
      - "8001:8001"
    environment:
      PGADMIN_DEFAULT_EMAIL: jiri.machacek@machysoft.cz
      PGADMIN_DEFAULT_PASSWORD: Heslo1234.
      PGADMIN_LISTEN_PORT: 8001
      LC_COLLATE: 'cs_CZ.UTF-8'
      LC_CTYPE: 'cs_CZ.UTF-8'
    volumes:
      - pgadmin-data2:/var/lib/pgadmin

volumes:
  local_pgdata2:
  pgadmin-data2: